# Generated by Django 2.2.7 on 2020-05-11 18:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookingobject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='老汉', max_length=50, verbose_name='记账对象')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='设置时间')),
            ],
            options={
                'verbose_name': '记账对象',
                'verbose_name_plural': '记账对象',
            },
        ),
        migrations.CreateModel(
            name='bookingtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='费用类型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='费用类型设置时间')),
            ],
            options={
                'verbose_name': '费用类型',
                'verbose_name_plural': '费用类型',
            },
        ),
        migrations.CreateModel(
            name='bookingdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='费用')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='记账时间')),
                ('bookingdetail', models.CharField(max_length=150, verbose_name='费用具体内容')),
                ('bookingremarks', models.CharField(max_length=150, verbose_name='费用备注')),
                ('bookingobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingobject', to='eb.bookingobject', verbose_name='局名')),
                ('bookingtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingtype', to='eb.bookingtype', verbose_name='局名')),
            ],
            options={
                'verbose_name': '具体费用',
                'verbose_name_plural': '具体费用',
            },
        ),
    ]
