# Generated by Django 2.2.7 on 2020-05-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eb', '0002_auto_20200512_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='金额'),
        ),
    ]
