# Generated by Django 2.2.7 on 2020-05-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eb', '0004_auto_20200512_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='金额'),
        ),
    ]
