# Generated by Django 2.2.7 on 2020-05-13 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eb', '0005_auto_20200513_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='verifyuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='报销'),
            preserve_default=False,
        ),
    ]
