# Generated by Django 2.2.7 on 2020-05-13 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eb', '0006_bookingdetail_verifyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetail',
            name='submituser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submituser', to=settings.AUTH_USER_MODEL, verbose_name='报销'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='verifyuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifyuser', to=settings.AUTH_USER_MODEL, verbose_name='审核'),
        ),
    ]
