# Generated by Django 2.2.7 on 2019-11-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc_card', '0002_gamepalyers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepalyers',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
