# Generated by Django 2.2.7 on 2019-11-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc_card', '0003_auto_20191126_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetails',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='翻数'),
        ),
    ]
