# Generated by Django 2.2.7 on 2019-12-02 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sc_card', '0004_auto_20191128_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetails',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gametodetail', to='sc_card.game', verbose_name='局名'),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='gameloser1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gametoloser1', to=settings.AUTH_USER_MODEL, verbose_name='失败选手1'),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='gameloser2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gametoloser2', to=settings.AUTH_USER_MODEL, verbose_name='失败选手2'),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='gamewinner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gametowinner', to=settings.AUTH_USER_MODEL, verbose_name='获胜选手'),
        ),
        migrations.AlterField(
            model_name='gamepalyers',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gametoplayer', to='sc_card.game', verbose_name='局名'),
        ),
        migrations.AlterField(
            model_name='gamepalyers',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playertouser', to=settings.AUTH_USER_MODEL, verbose_name='选手'),
        ),
    ]
