# Generated by Django 2.2.7 on 2020-06-11 18:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bloodsuger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='检查血糖时间')),
                ('bloodsugernum', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='血糖值')),
                ('marks', models.CharField(blank=True, max_length=150, null=True, verbose_name='备注')),
                ('submituser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='检测人')),
            ],
            options={
                'verbose_name': '血糖监测',
                'verbose_name_plural': '血糖监测',
            },
        ),
    ]
