# Generated by Django 2.2.7 on 2020-05-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191120_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(default='1', max_length=10, verbose_name='用户类型'),
        ),
    ]
